//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lifestyle
{
    using System;
    using System.Collections.Generic;
    
    public partial class register
    {
        public string username { get; set; }
        public string pwd { get; set; }
        public Nullable<byte> age { get; set; }
        public string email { get; set; }
        public string nationality { get; set; }
    }
}
