//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lifestyle
{
    using System;
    using System.Collections.Generic;
    
    public partial class userorder
    {
        public int transactionid { get; set; }
        public string pid { get; set; }
        public string username { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> totalprice { get; set; }
    }
}
